### ISSUE TITLE
Substitute a real public key

### ISSUE THREAD

**Issue by madhead** [ehn-digital-green-development/hcert-app-kotlin#5]
Is it possible to use a separately obtained `.pub` file to decode QRs?

**Comment by dirkx** [comment]
You do not need them to decode. Only to verify. You can do this entirely from raw tools such as OpenSSL. 

If you post the PEM and an example - happy to create the few lines of code. 

Or check the trivial python or OpenSSL examples that do just this in the repo.

**Comment by madhead** [comment]
I have a public key, obtained from the local QR-scanner app in the format:

```
-----BEGIN PUBLIC KEY-----
...Not sure if it's ok to paste it here, but it's just a public key...
-----END PUBLIC KEY-----
```

I thought of substituting it somewhere here: https://github.com/ehn-dcc-development/hcert-app-kotlin/blob/a6bcb686836c5a905b7441c0768647bda56c53be/app/src/main/java/ehn/techiop/hcert/android/MainActivity.kt#L212-L251 so that I would be able to actually decode the contents of my certificate. Right now the app is not able to decode it properly:

![image](https://user-images.githubusercontent.com/577360/125696742-37b03c8c-7bff-4fe0-a4b3-669b1eb6521a.png)

**Comment by madhead** [comment]
Ok, so, for people who is doing things like this just out of a curiosity… Just use this code to get the JSON. You don't need any keys, indeed. Import [this repo](https://github.com/ehn-dcc-development/hcert-kotlin) in your IDE and write a small `main`:

```kotlin
fun main() {
    val contextIdentifierService = DefaultContextIdentifierService()
    val base45Service = DefaultBase45Service()
    val compressorService = DefaultCompressorService()
    val coseService = DefaultCoseService(object : CryptoService {
        // All methods just throw TODO("Not yet implemented")
    })
    val cwtService = DefaultCwtService()
    val verificationResult = VerificationResult()
    val input = "HC1:6…K.0X3"  // Just decode the QR with any app
    val encoded = contextIdentifierService.decode(input, verificationResult)
    val compressed = base45Service.decode(encoded, verificationResult)
    val cose = compressorService.decode(compressed, verificationResult)
    val cwt = coseService.decode(cose, verificationResult)
    val cborObj = cwtService.decode(cwt, verificationResult)

    println(cborObj.toJsonString())
}
```
Run it and you'll get an error in `ehn.techiop.hcert.kotlin.chain.impl.DefaultCoseService#decode` related to the PKI and certs. Just comment out the `coseAdapter.validate` and re-run the app. You should be fine and get the data.
